openapi: 3.0.0
info:
  description: |
    ## 接口权限验证
    ### API网关对接参数

    ## 接口调用规范
    * 网络：测试环境网访问
  version: 1.0.0
  title: 数据对接文档
paths:
  /api/marketing/effect/summary:
    get:
      tags:
        - effect
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  ROL:
                    type: number
                  point:
                    type: number
                  awareness:
                    type: number
                  na:
                    type: number
                  sound:
                    type: number
                  effect:
                    type: number
                required:
                  - ROL
                  - point
                  - awareness
                  - na
                  - sound
                  - effect
              examples:
                example-1:
                  value:
                    ROL: 0
                    point: 0
                    awareness: 0
                    na: 0
                    sound: 0
                    effect: 0
  /api/marketing/effect/region:
    get:
      tags:
        - effect
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: object
                    properties:
                      current:
                        type: integer
                        example: 1
                        description: 当前页
                      total:
                        type: integer
                        example: 1
                        description: 总记录数
                      size:
                        type: integer
                        example: 0
                        description: 页码大小
                  records:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: integer
                          example: 1
                          description: 任务id
                        valeu:
                          type: string
              examples:
                example-1:
                  value:
                    page:
                      current: 1
                      total: 1
                      size: 0
                    records:
                      - name: 北京市
                        value: 123
  /api/marketing/effect/industry:
    get:
      tags:
        - effect
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  page:
                    type: object
                    properties:
                      current:
                        type: integer
                        example: 1
                        description: 当前页
                      total:
                        type: integer
                        example: 1
                        description: 总记录数
                      size:
                        type: integer
                        example: 0
                        description: 页码大小
                  records:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        type:
                          type: string
              examples:
                example-1:
                  value:
                    page:
                      current: 1
                      total: 1
                      size: 0
                    records:
                      - name: 数字政府
                        value: 123
  /api/marketing/effect/na:
    get:
      tags:
        - effect
      summary: Your GET endpoint
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                description: ''
                type: object
                properties:
                  page:
                    type: object
                    properties:
                      current:
                        type: number
                      total:
                        type: number
                      size:
                        type: number
                    required:
                      - current
                      - total
                      - size
                  records:
                    type: array
                    uniqueItems: true
                    minItems: 1
                    items:
                      required:
                        - name
                        - value
                      properties:
                        name:
                          type: string
                          minLength: 1
                        value:
                          type: number
                required:
                  - page
                  - records
              examples:
                example-1:
                  value:
                    page:
                      current: 0
                      total: 0
                      size: 0
                    records:
                      - name: 1月
                        value: 123
      operationId: get-api-marketing-effect-na
